name: Run Bio2RDF PHP scripts

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bio2rdf-dataset: ['hgnc']
        # bio2rdf-dataset: ['clinicaltrials', 'hgnc', 'sgd', 'pdb', 'pubmed', 'sabiork', 'affymetrix', 'pubchem', 'pharmgkb', 'lsr', 'drugbank', 'omim', 'mesh', 'interpro', 'ncbigene', 'irefindex', 'sider', 'mgi', 'homologene', 'genbank', 'taxonomy', 'chembl', 'wormbase', 'ctd', 'uniprot', 'dbsnp', 'ndc', 'biomodels', 'genage', 'ipi', 'pathwaycommons', 'biopax', 'refseq', 'bioportal', 'iproclass', 'goa', 'unists']

    steps:
    # - name: Setup PHP with PECL extension
    #   uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '5.3'
        # extensions: imagick, swoole

    ## Setting up the environment
    # https://github.com/bio2rdf/bio2rdf-scripts/wiki/Setting-up-the-developer-environment

    - uses: actions/checkout@v2
      with:
        repository: 'micheldumontier/php-lib'
        path: 'php-lib'

    - uses: actions/checkout@v2
      with:
        path: 'bio2rdf-scripts'
        # submodules: 'true'

    - name: Create data folders
      run: |
        mkdir -p data/download
        mkdir -p data/rdf
        pwd
        ls
        echo 'bio2rdf-scripts SCRIPTS'
        ls /home/runner/work/bio2rdf-scripts/bio2rdf-scripts/bio2rdf-scripts
        echo 'PHP LIIIB'
        ls /home/runner/work/bio2rdf-scripts/bio2rdf-scripts/php-lib

      # ls /home/runner/work/bio2rdf-scripts/bio2rdf-scripts

    ## Run the Bio2RDF PHP parsers
    # https://github.com/bio2rdf/bio2rdf-scripts/wiki/Run-the-Bio2RDF-parsers

    - name: Run ${{ matrix.bio2rdf-dataset }} parser
      working-directory: ./bio2rdf-scripts
      run: |
        php runparser.php parser=${{ matrix.bio2rdf-dataset }} download=true files=all indir=data/download/${{ matrix.bio2rdf-dataset }}/ outdir=data/rdf/${{ matrix.bio2rdf-dataset }}/


    - name: Upload output RDF data
      uses: actions/upload-artifact@v1
      with:
        name: rdf-output
        path: bio2rdf-scripts/data

    # - name: Validate composer.json and composer.lock
    #   run: composer validate

    # - name: Cache Composer packages
    #   id: composer-cache
    #   uses: actions/cache@v2
    #   with:
    #     path: vendor
    #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-php-

    # - name: Install dependencies
    #   if: steps.composer-cache.outputs.cache-hit != 'true'
    #   run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test


